### ISSUE TITLE
Temperature value is incorrect

### ISSUE THREAD

**Issue by clayderson** [robertoduessmann/weather-api#15]
Currently, a city of São Paulo has a temperature of 19 ° C. However, an API displays a temperature of -31 ° C (yes, below 0).

Forgive my english.

**Comment by nilemarbarcelos** [comment]
@clayderson We have noticed that if you use: 
```https://goweather.herokuapp.com/weather/SaoPaulo``` 
it would not work, but if you use 
```https://goweather.herokuapp.com/weather/SãoPaulo``` (with tilde), it should work without problems

**Comment by clayderson** [comment]
Truth. I noticed that the same page is displayed when we use city names that do not exist. Returning a 404 error would not be ideal? Thank you!

**Comment by nilemarbarcelos** [comment]
I agree with you @clayderson. Feel free to contribute if you can, but we should be adding it as soon as possible :smile:

**Comment by robertoduessmann** [comment]
Ohh... So when you try to use some unknown city, a random temperature was show :/

I agree with you guys, when the API can't find the location, a 404 error could be returned.

Feel free to help me and to improve this API validation @clayderson and @nilemarbarcelos .

**Comment by alarangeiras** [comment]
This issue is still open? Can I try to fix it?
I'm interested in contribute to some OS projects.

**Comment by robertoduessmann** [comment]
Hi @alarangeiras , thanks for your interesting on project.

For sure, go ahead, I would be very grateful if you could help :tada: 

You can see on comments some suggestions to handle with problem, feel free to try or figure out another approach and submit your pull request :rocket: 
Let me know if I could help or clarify in anyway as well ;)

**Comment by robertoduessmann** [comment]
Fixed in #26 :

![image](https://user-images.githubusercontent.com/9089383/51473722-74404f80-1d7d-11e9-8af9-acbeaa839c2b.png)

Thanks @alarangeiras :tada:
