### ISSUE TITLE
Need to be able to get temperature in F or C

### ISSUE THREAD

**Issue by curtisgibby** [robertoduessmann/weather-api#17]
It would be useful if you could pass in a flag to request the temperature values be formatted as Fahrenheit instead of Celcius. (Or, like the source wttr.in does, if the API automatically fell back to the default temperature format for the specified location.)

**Comment by curtisgibby** [comment]
Same with wind values: miles per hour as opposed to kilometers per hour.

**Comment by marcosinger** [comment]
@robertoduessmann my PR for weekdays cover this part as well.. Let me know what you think about it. We could move it to another PR and discuss more about it :)

**Comment by robertoduessmann** [comment]
Thanks a lot @marcosinger for now I really believe its awesome what you did! :smile:
