### ISSUE TITLE
Forecast days should have a date

### ISSUE THREAD

**Issue by curtisgibby** [robertoduessmann/weather-api#18]
Based on the current data, I can't really tell what days the `forecast` is related to.

```javascript
"forecast": [
	{
		"day": 1,
		"temperature": "10 °C",
		"wind": "25 km/h"
	},
	{
		"day": 2,
		"temperature": "3 °C",
		"wind": "9 km/h"
	}
]
```

Is day 1 in this example the remainder of "today", or is it "tomorrow"? I think that replacing `day` with a date value makes sense.

**Comment by marcosinger** [comment]
Hey @robertoduessmann .. I'd like to help on this one. Sounds good to you?

**Comment by robertoduessmann** [comment]
Sounds awesome @marcosinger , please go ahead and thanks for the interesting in the project :tada: :rocket:
