### ISSUE TITLE
API returning empty strings

### ISSUE THREAD

**Issue by naktis** [robertoduessmann/weather-api#39]
Today I noticed that this API, working on Herokuapp, started returning JSON objects with valid keys, but empty string values with OK 200 status:
`{
  "temperature": "",
  "wind": "",
  "description": "",
  "forecast": [
    {
      "day": "",
      "temperature": "",
      "wind": ""
    },
    {
      "day": "",
      "temperature": "",
      "wind": ""
    },
    {
      "day": "",
      "temperature": "",
      "wind": ""
    }
  ]
}`

The response is the same for a number of cities that worked before and no network errors are thrown.

As a result, the [API usage example](https://goweather.herokuapp.com/weather/Curitiba) and the [web client](https://reacttempo.netlify.app/), mentioned in the Readme file, aren't functioning as well.

**Comment by naktis** [comment]
Update: the API started working correctly again, the issue isn't relevant anymore.

**Comment by robertoduessmann** [comment]
Thanks for reporting and letting me know is fixed @naktis. I'm afraid the source where the info is scrapped from changes time to time for few min. I might try to improve it in the future by caching the response for few minutes for the same city.
