### ISSUE TITLE
Api Not Working

### ISSUE THREAD

**Issue by halilozel1903** [robertoduessmann/weather-api#40]
Hi,

I'm using your api but not working 

`{"temperature":"","wind":"","description":"","forecast":[{"day":"","temperature":"","wind":""},{"day":"","temperature":"","wind":""},{"day":"","temperature":"","wind":""}]}`

What's the problem?

**Comment by robertoduessmann** [comment]
Thanks for reporting @halilozel1903 , looking into it.

**Comment by robertoduessmann** [comment]
@halilozel1903 it seems the service in which we extract the weather info from is suffering some issues:

> Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.

refs https://wttr.in/

**Comment by robertoduessmann** [comment]
Hey @halilozel1903 , https://wttr.in/ is back, can you try again?
https://goweather.herokuapp.com/weather/Berlin

**Comment by halilozel1903** [comment]
Thanks. It's worked. @robertoduessmann 

https://goweather.herokuapp.com/weather/Istanbul 

`{"temperature":"18 Â°C","wind":"17 km/h","description":"Partly cloudy","forecast":[{"day":"1","temperature":"18 Â°C","wind":"20 km/h"},{"day":"2","temperature":"22 Â°C","wind":"23 km/h"},{"day":"3","temperature":"22 Â°C","wind":" km/h"}]}`

**Comment by robertoduessmann** [comment]
Thanks for confirming and letting me know @halilozel1903
