### ISSUE TITLE
missing some cities

### ISSUE THREAD

**Issue by MaximeGer** [robertoduessmann/weather-api#44]
The api misses some cities for example a not so little french city named Nantes is missing

![image](https://user-images.githubusercontent.com/49746475/173028288-b2791e13-519d-43c3-a429-ac3f98489189.png)

**Comment by robertoduessmann** [comment]
Thanks for reporting it @Zealyy , I can confirm the issue. Let me add some tags here to the bug ticket and I'll try to check it over the next days.
Also if someone if someone is willing, feel free to help me to find out the cause.

**Comment by robertoduessmann** [comment]
Hey @Zealyy I can now see https://goweather.herokuapp.com/weather/nantes, can you confirm its back available?

**Comment by MaximeGer** [comment]
I can confirm sir 👍

**Comment by robertoduessmann** [comment]
Amazing, thanks for confirming @Zealyy
