### ISSUE TITLE
Deployment isn´t working

### ISSUE THREAD

**Issue by V01D-PH03N1X** [robertoduessmann/weather-api#46]
![image](https://github.com/robertoduessmann/weather-api/assets/87519233/4d2e07a3-1510-4f51-90ab-3fdd6981046c)

**Comment by robertoduessmann** [comment]
Thanks for letting me know @DarkModz-Official , looking into it

**Comment by robertoduessmann** [comment]
Fixed, pls can you try again @DarkModz-Official

**Comment by V01D-PH03N1X** [comment]
Works. Thanks for the fast problem resolve 😃

**Comment by V01D-PH03N1X** [comment]
Eventually it broke again but im not sure because my internet is at the moment bad af.

**Comment by robertoduessmann** [comment]
Hmm, let me check the server metrics @DarkModz-Official , thanks for the follow up.

If i try to open it now it works though: 

![image](https://github.com/robertoduessmann/weather-api/assets/9089383/07c63c23-773f-4b94-a30d-2ae3e7df5eb9)
