### ISSUE TITLE
Could not find Seoul

### ISSUE THREAD

**Issue by voidofvanity** [robertoduessmann/weather-api#47]
https://goweather.herokuapp.com/weather/Seoul

{"message":"NOT_FOUND"}

Citites that could not be found from SK: Seoul, Gwangju, Gimje, Jeongeup and i guess many more.
P.s. I am using city names from wikipedia.

**Comment by robertoduessmann** [comment]
Hey @majornelson4 thanks for letting me know.

I just tried with Seoul now and it worked, it might be some inconsistency in the source website. Could you pls try again?

![image](https://github.com/robertoduessmann/weather-api/assets/9089383/167409f9-f4c7-4e50-8b71-5e7672a176f5)

**Comment by voidofvanity** [comment]
It worked yesterday, now I am getting application error.

**Comment by robertoduessmann** [comment]
Sorry @majornelson4 something is killing the app time to time, I need to further investigate it, for now i did a restart. could you pls validate its working again?
Sorry for the trouble 🙇

**Comment by wkrt** [comment]
Hi @robertoduessmann, the app seems to be down again.

**Comment by robertoduessmann** [comment]
Sorry for the delay to get back here @wkrt .
I'm afraid the API the app uses behind the scenes had some glitchy regarding its structure.
It seems to be back, could you pls give a new try 🙏

**Comment by voidofvanity** [comment]
Tried various cities, works fine.

**Comment by robertoduessmann** [comment]
Perfect, thanks @majornelson4
