### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/weather-api#5]
Create a CONTRIBUTING.md file, with the basic and general steps to contribute to project.

**Comment by rohitdaryanani** [comment]
@robertoduessmann  Could you check #6 if its okay? I based it on [thoughtbot](https://github.com/thoughtbot/templates/blob/master/CONTRIBUTING.md.template)

**Comment by robertoduessmann** [comment]
Perfect @rohitdaryanani , thanks for contribution :)
