### ISSUE TITLE
Create basic unit tests

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/weather-api#7]
Add basic unit tests in Go to this project, because today we are without coverage.

I thought to start for the basic controller: [weather.go](https://github.com/robertoduessmann/weather-api/blob/master/controller/weather.go)

**Comment by Ninban** [comment]
I'm learning the basics of testing, so I'll put my hands in this.
Also interested as I never touched Go before.

**Comment by robertoduessmann** [comment]
Nice, go ahead @Carouelle! Thanks for your interesting :)

**Comment by vhugo** [comment]
@Carouelle I didn't know if you were still working on this. I create a basic test, but I think you could also add more tests if @robertoduessmann approves the PR. 

I don't know a lot about tests or Go, but this is not my first time writing tests in Go.  If need help with it just let me know.

**Comment by robertoduessmann** [comment]
Thanks @Carouelle and @vhugo .

Feel free to open new issues and add more tests case in anothers parts of system.
I really appreciate the interest of you on project :rocket:
